spring:
  application:
    name: kakari

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/static/**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  session:
    redis:
      flush-mode: on-save
      namespace: kakari

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mayb.dev:3306/kakari?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: secret

  data:
    redis:
      host: mayb.dev
      port: 6379
      database: 0

  jpa:
    hibernate:
      ddl-auto: create-drop
    # ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

